version: "3.3"

services:
  web:
    image: orangehrm/orangehrm:5.3
    ports:
      - "8200:80"
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - mailto:smtp_user=your_email@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_PROTOCOL=ssl
    volumes:
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
    privileged: true
    links:
      - db
    restart: always
    hostname: orangehrm-prod-web
    container_name: prod_web

  db:
    image: orangehrm/orangehrm-db-images:mariadb-10.2
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    hostname: orangehrm-prod-db
    container_name: prod_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
    restart: always
    container_name: prod_phpmyadmin