name: "Eslint check"

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 14.16.1
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"
      - name: Run Eslint check
        id: run-eslint-check
        run: |
          npm install eslint
          npx eslint src/**
